# Generated by Django 6.1.1 on 2026-09-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Área o proyecto')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Centro de costo',
                'verbose_name_plural': 'Centros de costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=150, verbose_name='Nombre del solicitante')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('justificacion', models.TextField(max_length=1000, verbose_name='Justificación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.area', verbose_name='Área o proyecto')),
                ('centro_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requerimientos', to='requerimientos.centrocosto', verbose_name='Centro de costo')),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
