# Generated by Django 5.2 on 2026-09-08 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0002_consecutivo_radicacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Consecutivo del ítem dentro del requerimiento.",
                        verbose_name="N.º",
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "requerimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="requerimientos.requerimiento",
                        verbose_name="Requerimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ítem",
                "verbose_name_plural": "Ítems",
                "ordering": ["requerimiento", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("requerimiento", "numero"),
                        name="item_numero_unico_por_requerimiento",
                    )
                ],
            },
        ),
    ]
