# Generated by Django 5.2 on 2026-09-08 01:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0003_item"),
    ]

    # Los default=1 son valores de una sola vez para poder crear las columnas
    # NOT NULL: la tabla de items se crea en la migracion 0003 de este mismo
    # sprint, asi que no hay filas previas que rellenar (preserve_default=False
    # los quita del modelo).
    operations = [
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True, verbose_name="Código")),
                ("nombre", models.CharField(max_length=50, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="item",
            name="cantidad",
            field=models.PositiveIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "La cantidad debe ser mayor que cero."
                    )
                ],
                verbose_name="Cantidad",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="unidad_medida",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="requerimientos.unidadmedida",
                verbose_name="Unidad de medida",
            ),
            preserve_default=False,
        ),
    ]
