# Generated by Django 5.2 on 2026-09-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0004_unidadmedida_item_cantidad_item_unidad_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="es_reembolsable",
            field=models.BooleanField(
                default=False,
                help_text="La compra se factura a un tercero o se reembolsa al solicitante.",
                verbose_name="¿Es reembolsable?",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="requiere_calibracion",
            field=models.BooleanField(
                default=False,
                help_text="El ítem debe entregarse con certificado de calibración vigente.",
                verbose_name="¿Requiere calibración?",
            ),
        ),
    ]
