# Generated by Django 5.2 on 2026-09-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0005_item_es_reembolsable_item_requiere_calibracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="especificaciones_tecnicas",
            field=models.TextField(
                blank=True,
                help_text="Marca, modelo, referencia, rango, material, norma aplicable, etc.",
                verbose_name="Especificaciones técnicas",
            ),
        ),
    ]
