# Generated by Django 5.2 on 2026-09-08 01:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0006_item_especificaciones_tecnicas"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="precio_referencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0, "El precio no puede ser negativo.")
                ],
                verbose_name="Precio unitario de referencia",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                editable=False,
                max_digits=16,
                verbose_name="Total del ítem",
            ),
        ),
    ]
