# Generated by Django 5.2 on 2026-09-09 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requerimientos", "0007_item_precio_referencia_item_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requerimiento",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requerimientos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Radicado por",
            ),
        ),
    ]
